site_name: Console Interactive
repo_url: https://github.com/Davidblkx/ConsoleInteractive
nav:
  - Home: index.md
  - ConsoleI: console-i.md
  - Advanced:
    - Validation: validation.md
    - Conversion: converter.md
theme:
  name: mkdocs
extra_css:
  - extra-styles.css