site_name: Console Interactive
repo_url: https://github.com/Davidblkx/ConsoleInteractive
nav:
  - Home: index.md
  - ConsoleI: console-i.md
  - Components:
    - InputText: comps/input-text.md
    - InputSelect: comps/input-sel.md
    - Custom: comps/custom.md
  - Advanced:
    - Validation: adv/validation.md
    - Conversion: adv/converter.md
    - Forms: adv/forms.md
theme:
  name: mkdocs